apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: hpa-site-android
  namespace: default

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-site-android
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
